import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  {
    // `.cjs` is CommonJS by definition, so `require()` is the only import form available.
    // eslint-config-next applies the TypeScript rules everywhere, which flags the one-off
    // maintenance script under scripts/ as an error and buries real errors under it.
    files: ["**/*.cjs"],
    rules: { "@typescript-eslint/no-require-imports": "off" },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Separate app with its own eslint config.
    "admin/**",
    // Separate project with its own tsconfig/package.json.
    "functions/**",
    // Scratch directory of the /impeccable skill — throwaway pixel-measurement scripts, all
    // CommonJS. 26 of the 26 errors `npx eslint` reported were from here (2026-09-25), which
    // is exactly the burial this config's other ignores exist to prevent. Git ignores it too.
    ".impeccable/**",
    // Generated by /design-sync — build output and staged converter scripts.
    "ds-bundle/**",
    ".ds-sync/**",
    // One-off analysis scripts (pixel measurement, mockup builders). They are run by hand,
    // never bundled, and routinely destructure more of a measurement than they print — which
    // is 18 unused-var warnings that drown out the ones in src/.
    "doc/**",
  ]),
]);

export default eslintConfig;
