// Design-system barrel for /design-sync. Re-export only — no component code
// lives here. Generated by hand, committed, edited when the DS surface changes.

import "./preview-env";

// -- shared components (src/components) -------------------------------------
export { BrandBi } from "../src/components/BrandBi";
export { CompanyFooter } from "../src/components/CompanyFooter";
export { CompanyInfoBar } from "../src/components/CompanyInfoBar";
export { default as ConfirmModal } from "../src/components/ConfirmModal";
export { default as InfoModal } from "../src/components/InfoModal";
export { default as ModalViewportChrome } from "../src/components/ModalViewportChrome";
export { default as NoBirthTimePopup } from "../src/components/NoBirthTimePopup";
export { default as NoticeList } from "../src/components/NoticeList";
export { default as RoomLimitModal } from "../src/components/RoomLimitModal";
export { default as SubPageTopBar } from "../src/components/SubPageTopBar";
export { default as SupportCenter } from "../src/components/SupportCenter";
export { default as SuspensionModal } from "../src/components/SuspensionModal";

// -- icons (src/app/(app)/tarot/icons.tsx) ----------------------------------
export {
  BackIcon, MenuIcon, SendIcon, RoomInfoIcon, NewChatIcon, SajuIcon, ZiweiIcon,
  CompatibilityIcon, TimepassIcon, CloseIcon, CheckIcon, PlusIcon,
  SpreadOneIcon, SpreadThreeIcon, SpreadDualIcon, SpreadCelticIcon,
  ChevronRightIcon, SearchIcon, InvitePersonIcon, CartIcon, CardIcon,
  ListIcon, IdCardIcon, PersonIcon, CompassIcon, GearIcon, LogoutDoorIcon,
  PencilIcon, TrashIcon, InfoCircleIcon, BellIcon, TicketIcon,
} from "../src/app/(app)/tarot/icons";

// -- tarot screen pieces (src/app/(app)/tarot/page.tsx) ---------------------
export {
  CountPassUsageModal, ReadingLoadingMessage, CardImage, CelticCrossLayout,
  DualPathLayout, WelcomePopup, TimePassCard, HeldTimepassListModal,
  HeldTimepassUseModal, NoHeldTimepassModal, PurchaseTicketModal,
  RenameRoomModal, SpreadSelectSheet, Switch,
} from "../src/app/(app)/tarot/page";

// -- other screen pieces ----------------------------------------------------
export { ListRow, Section, ComingSoon } from "../src/app/(app)/me/page";
export { SectionPanel } from "../src/app/(app)/settings/page";
export { PolicyModal, FieldLabel } from "../src/app/signup/page";
export { AppShell } from "../src/app/(app)/layout";

// -- preview-only cards (no app source; see componentSrcMap null entries) ---
export { TokenSpecimen } from "./token-specimen";

// -- preview-only provider (not a DS component; used via cfg.provider) ------
export { DsPreviewProvider } from "./preview-provider";
