// Builds the stylesheet the DS bundle ships (cfg.cssEntry).
//
// Three things the converter can't do itself:
//
//  1. Tayeon styles with Tailwind v4, so globals.css is a SOURCE file — the
//     utilities only exist after the Tailwind compiler scans the app.
//
//  2. Tailwind only emits utilities it SEES used. Scanning src/ alone ships
//     just the subset the app happens to use today, so a design agent writing
//     a perfectly valid `bg-bg` or `headlineLarge` would get no CSS at all.
//     The safelist below forces the whole semantic-token surface to exist, in
//     every prefix and the variants components actually use.
//
//  3. The brand font (Pretendard) is loaded by next/font at runtime, which
//     sets --font-pretendard. Nothing sets it outside the Next app, so every
//     preview — and every design built with this DS — would fall back to a
//     system sans. The @font-face block is what ships the real font.
//
// Run: node .design-sync/make-css.mjs
import { execFileSync } from "node:child_process";
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const DIR = ".design-sync/compiled";
const OUT = `${DIR}/tayeon.css`;
mkdirSync(DIR, { recursive: true });

// The token list is READ from globals.css rather than restated here. A
// hand-kept copy silently rots: a token added to the app but missing from the
// safelist compiles to nothing, and a design agent using it gets no styling
// with no error anywhere. @theme inline is the authoritative surface, since
// that block is exactly what turns a token into Tailwind utilities.
const GLOBALS = readFileSync("src/app/globals.css", "utf8");

const blockOf = (selector) => {
  // Anchored at a line start. A bare indexOf(".dark") matches inside the
  // `@custom-variant dark (&:where(.dark, .dark *))` declaration on line 3,
  // and reading from there lands on the :root block instead — both themes
  // then come out identical, with nothing anywhere to say so.
  const at = GLOBALS.indexOf(`
${selector} {`);
  if (at < 0) throw new Error(`globals.css: no "${selector} {" at a line start`);
  const open = GLOBALS.indexOf("{", at);
  return GLOBALS.slice(open + 1, GLOBALS.indexOf("}", open));
};

const declsOf = (selector) =>
  Object.fromEntries(
    [...blockOf(selector).matchAll(/--([a-z0-9-]+)\s*:\s*([^;]+);/g)].map(
      ([, k, v]) => [k, v.trim()],
    ),
  );

// @theme inline maps --color-<token> -> var(--<token>); the left-hand names
// are the utilities that exist, so they are the safelist's source of truth.
const TOKENS = [...blockOf("@theme inline").matchAll(/--color-([a-z0-9-]+)\s*:/g)]
  .map(([, name]) => name);

// Light/dark values, emitted for the TokenSpecimen preview card so the
// swatches and contrast figures can never disagree with the shipped CSS.
const LIGHT = declsOf(":root");
const DARK = declsOf(".dark");
const missing = TOKENS.filter((t) => !(t in LIGHT));
if (missing.length) {
  throw new Error(`@theme inline names tokens with no :root value: ${missing.join(", ")}`);
}
writeFileSync(
  `${DIR}/tokens.ts`,
  `// GENERATED by .design-sync/make-css.mjs from src/app/globals.css. Do not edit.
` +
    `export const TOKEN_NAMES = ${JSON.stringify(TOKENS, null, 2)} as const;
` +
    `export const LIGHT: Record<string, string> = ${JSON.stringify(LIGHT, null, 2)};
` +
    `export const DARK: Record<string, string> = ${JSON.stringify(DARK, null, 2)};
`,
);
console.log(`wrote ${DIR}/tokens.ts (${TOKENS.length} tokens)`);
const PREFIXES = ["bg", "text", "border", "fill", "divide"];
const VARIANTS = ["", "hover:", "disabled:", "focus:", "lg:"];
const TYPE = ["headline", "title", "body", "label"].flatMap((f) =>
  ["Large", "Medium", "Small"].map((s) => f + s),
);

const safelist = [
  ...PREFIXES.flatMap((p) => TOKENS.flatMap((t) => VARIANTS.map((v) => `${v}${p}-${t}`))),
  ...TYPE,
  "animate-fade-in",
].join("\n");
writeFileSync(`${DIR}/safelist.txt`, safelist + "\n");

// Wrapper entry: the app's real stylesheet plus explicit sources, since
// automatic content detection is relative to the CSS file's own location.
writeFileSync(
  `${DIR}/entry.css`,
  `@import "../../src/app/globals.css";\n@source "../../src";\n@source "./safelist.txt";\n`,
);

execFileSync(
  process.execPath,
  [".ds-sync/node_modules/@tailwindcss/cli/dist/index.mjs", "-i", `${DIR}/entry.css`, "-o", OUT, "--minify"],
  { stdio: "inherit" },
);

// url()s point at the REAL font files relative to this stylesheet, so the
// converter can resolve and rewrite them into the bundle's fonts/ dir.
appendFileSync(
  OUT,
  `
@font-face{font-family:"Pretendard";src:url("../../asset/font/Pretendard-SemiBold.otf") format("opentype");font-weight:600;font-style:normal;font-display:swap}
@font-face{font-family:"Pretendard";src:url("../../asset/font/Pretendard-Bold.otf") format("opentype");font-weight:700;font-style:normal;font-display:swap}
:root{--font-pretendard:"Pretendard",system-ui,-apple-system,"Segoe UI",sans-serif}
`,
);
console.log("wrote", OUT);
