export const MAX_SUPPORT_ATTACHMENTS = 3;
export const MAX_SUPPORT_ATTACHMENT_BYTES = 2 * 1024 * 1024;
export const MAX_SUPPORT_TOTAL_ATTACHMENT_BYTES = MAX_SUPPORT_ATTACHMENTS * MAX_SUPPORT_ATTACHMENT_BYTES;
