"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebase/client";
import { AdminPageHeader } from "@/components/AdminPageHeader";

type Reading = { uid: string; nickname: string | null; id: string; roomId: string | null; question: string; interpretation: string; createdAt: string; topic: string | null };
type Abuse = { uid: string; nickname: string | null; count: number; latestAt: string; latestQuestion: string };
const date = (value: string) => value.replace("T", " ").slice(0, 19);

export default function ModerationPage() {
  const router = useRouter(); const [free, setFree] = useState<Reading[]>([]); const [abuse, setAbuse] = useState<Abuse[]>([]); const [tab, setTab] = useState<"risk" | "free">("risk"); const [loading, setLoading] = useState(true);
  useEffect(() => onAuthStateChanged(auth, async (user) => { if (!user) return router.push("/login"); const response = await fetch("/api/admin/moderation", { headers: { authorization: `Bearer ${await user.getIdToken()}` } }); if (response.ok) { const data = await response.json(); setFree(data.freeReadings); setAbuse(data.abuseUsers); } setLoading(false); }), [router]);
  async function review(reading: Reading) { const user = auth.currentUser; if (!user || !reading.roomId) return; const response = await fetch(`/api/admin/users/${encodeURIComponent(reading.uid)}/rooms/${encodeURIComponent(reading.roomId)}/readings/${encodeURIComponent(reading.id)}/review`, { method: "POST", headers: { authorization: `Bearer ${await user.getIdToken()}` } }); if (!response.ok) return alert((await response.json()).error ?? "확인 처리에 실패했습니다."); setFree((items) => items.filter((item) => item.id !== reading.id || item.roomId !== reading.roomId)); }
  return <main className="admin-page pb-12"><AdminPageHeader title="검토" description="무료 처리된 리딩과 반복적인 부정 요청 신호를 분리해 확인합니다." /><div className="mx-auto max-w-[1180px] px-6"><div className="mb-6 inline-flex rounded-full bg-[#E8E8ED] p-1"><button onClick={() => setTab("risk")} className={`rounded-full px-4 py-2 text-sm font-medium ${tab === "risk" ? "bg-white text-[#1D1D1F] shadow-sm" : "text-[#6E6E73]"}`}>부정 요청 <span className="ml-1 tabular-nums">{abuse.length}</span></button><button onClick={() => setTab("free")} className={`rounded-full px-4 py-2 text-sm font-medium ${tab === "free" ? "bg-white text-[#1D1D1F] shadow-sm" : "text-[#6E6E73]"}`}>무료 처리 <span className="ml-1 tabular-nums">{free.length}</span></button></div><section className="overflow-hidden rounded-[28px] bg-white">{loading ? <p className="p-16 text-center text-sm text-[#86868B]">불러오는 중...</p> : tab === "risk" ? abuse.length === 0 ? <p className="p-16 text-center text-sm text-[#86868B]">검토가 필요한 사용자가 없습니다.</p> : abuse.map((item) => <article key={item.uid} className="border-b border-[#E8E8ED] px-6 py-5 last:border-0"><div className="flex items-center justify-between gap-4"><div><p className="font-semibold">{item.nickname ?? "(닉네임 없음)"}</p><p className="mt-1 font-mono text-xs text-[#86868B]">{item.uid}</p></div><span className="rounded-full bg-[#FFF2F0] px-3 py-1 text-sm font-semibold text-[#D70015]">{item.count}회</span></div><p className="mt-4 text-sm leading-6 text-[#424245]">{item.latestQuestion}</p></article>) : free.length === 0 ? <p className="p-16 text-center text-sm text-[#86868B]">미확인 무료 처리 건이 없습니다.</p> : free.map((item) => <article key={`${item.roomId}:${item.id}`} className="border-b border-[#E8E8ED] px-6 py-5 last:border-0"><div className="flex items-start justify-between gap-5"><div><p className="font-semibold">{item.nickname ?? "(닉네임 없음)"}</p><p className="mt-1 font-mono text-xs text-[#86868B]">{item.uid} · {date(item.createdAt)}{item.topic ? ` · ${item.topic}` : ""}</p></div><button onClick={() => review(item)} className="rounded-full bg-[#0071E3] px-3.5 py-2 text-xs font-semibold text-white">확인 처리</button></div><p className="mt-5 text-sm font-medium text-[#1D1D1F]">{item.question}</p><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-[#6E6E73]">{item.interpretation}</p></article>)}</section></div></main>;
}
